import { Project } from "./types";

export const devProjects: Project[] = [
  {
    id: "0",
    cardImage: "starred.png",
    title: "Starred - Browser Wishlist",
    description: "A stylized and accessible wishlisting platform that features authentication, database storage, and webpage parsing.",
    techstack: "React, Typescript, Python, Next.js, Firebase",
    mockup: "comp.jpg",
    purpose: "lorem",
    process: "lorem",
    demo: "demo.mov",
    imageSm: "comp.jpg",
    imageLg: "comp.jpg",
  },
  {
    id: "1",
    cardImage: "cairn2.png",
    title: "Cairn - Trip Scheduler",
    description: "desc 2",
    techstack: "ts",
    mockup: "string",
    demo: "comp.jpg",
    imageSm: "comp.jpg",
    imageLg: "comp.jpg",
  },
  {
    id: "2",
    cardImage: "cc.png",
    title: "Candid Candies",
    description: "Overview: A Candy Heart inspired message-board web application",
    techstack: "Javascript | HTML | CSS | React | MongoDB | Adobe Fresco | Adobe Illustrator",
    purpose: "Candid Candies is a message-board web application that allows for the drafting and posting of messages onto a candy heart inspired landing page. The UI includes hand-drawn visual elements with coded functionality using React.js, showcases an ability to combine front-end development skills with hand-drawn designs. This project is currently in development, in collaboration with Arushi Aggarwal.",
    mockup: "string",
    demo: "comp.jpg",
    imageSm: "comp.jpg",
    imageLg: "comp.jpg",
  },
  {
    id: "3",
    cardImage: "cairn.png",
    title: "Polaris - Peer Mentorship",
    description: "desc 4",
    techstack: "ts",
    mockup: "string",
    demo: "comp.jpg",
    imageSm: "comp.jpg",
    imageLg: "comp.jpg",
  },
  {
    id: "4",
    cardImage: "stock.png",
    title: "StockView - Stock Simulator",
    description: "Overview: desc 5",
    purpose: "StockView is a stock trading simulation program, coded in Java, that utilizes SOLID principles and MVC architecture to create an environment for simulating stock trading. The program supports over 700 stock tickers, and functionalities such as building multiple portfolios, determining x-day averages, buying, selling, and valuating stocks and portfolios on certain dates, and creating bar-graph representations of stock and portfolio performance among other functionalities. The project features both text-based and Swing GUI interfaces, enabling users to query real-time stock data through integrated API retrieval using AlphaVantageAPI. To enhance performance, we implemented a data caching mechanisms, allowing for more efficient API usage and improved query responsiveness. Built in collaboration with Ayomide Addey. Available on Github upon request.",
    techstack: "Java | JavaSwing | AlphaVantage API",
    mockup: "string",
    demo: "comp.jpg",
    imageSm: "comp.jpg",
    imageLg: "comp.jpg",
  },
];

export const designProjects: Project[] = [
  {
    id: "6",
    cardImage: "roster.png",
    title: "The Roster - Soccer Social Network",
    description: "desc 1",
    techstack: "ts",
    mockup: "string",
    demo: "comp.jpg",
    imageSm: "comp.jpg",
    imageLg: "comp.jpg",
  },
  {
    id: "7",
    title: "Cairn - Trip Scheduler",
    cardImage: "cairn.png",
    description: "desc 2",
    techstack: "ts",
    mockup: "string",
    demo: "comp.jpg",
    imageSm: "comp.jpg",
    imageLg: "comp.jpg",
  },
  {
    id: "8",
    cardImage: "inspira.png",
    title: "Inspira - Artist Resources",
    description: "Overview: Resource curations for creatives",
    techstack: "Figma",
    purpose: "Inspira is a resource-curation website for creatives, looking to use generative AI to complement artistic processes, rather than take away from them. This project began with an understanding of the relationship between artists and generative AI. As an artist myself, I have experienced the frustration of generative AI being used to produce artwork through the exploitation of artists online. I wanted to restructure the relationship between artists and AI by providing an environment where this technology can uplift the creative process in a systemized manner, rather than rob from it.",
    process: "The current prototype supports primary workflows, such as logging in and signing up, creating a new workspace, saving generated resources to a profile, and exploring a page of publically available workspaces categorized by art form.  These workflows were visualized through both a hand-drawn and digital sitemap. These workflows were identified through benchmarking, as well as my own role as a user of these platforms. I identified the aspects of these UI's that I thought worked well, and ones that I did not want to bring into my own project.",
    mockup: "string",
    demo: "comp.jpg",
    imageSm: "comp.jpg",
    imageLg: "comp.jpg",
  },
  {
    id: "9",
    cardImage: "ssf.png",
    title: "Securing Safe Food - Allergen-Safe Food Bank",
    description: "desc 4",
    techstack: "ts",
    mockup: "string",
    demo: "comp.jpg",
    imageSm: "comp.jpg",
    imageLg: "comp.jpg",
  }
];
